### ISSUE TITLE
String->Number parsing function

### ISSUE THREAD

**Issue by kentros** [RockstarLang/rockstar#115]
User input comes as strings from STDIN with `Listen to`.  It would be nice to be able to convert user input to a number so we can pass it in to functions that take numbers.
Proposal: reserve the phrase(s) 
* `{a} has become comfortably numb to {b}`
* `{a} have become comfortably numb to {b}`

Example program to determine if user input is an even or an odd number:
```
Listen to Tommy
He has become comfortably numb to the stuff
If Modulus taking the stuff and 2 is 0 (using Mod function from README)
Say "Even"
Else
Say "Odd"
```

**Comment by kennethgoodman** [comment]
On this note, need float -> int or more control over the actual representation of the object. Some sort of memory alloc/pointers + integer division would be nice

**Comment by cwfitzgerald** [comment]
There is an interesting question to be had if this belongs in the language --- and part of the language runtime --- or part of an always available standard library. While a lot of these functions can be best implemented with compiler hooks, they don't necessarily have to be part of the language. I don't terribly have an opinion one way or the other.

**Comment by wolfgang42** [comment]
I'm interested in this feature too--in particular @zhuowei has contributed a [treesort implementation](https://github.com/wolfgang42/rockstar-js/blob/master/examples/treesort.rock) which would benefit greatly from being able to read its list of numbers from standard input. (Currently the list of numbers to sort is hard-coded.)

@cwfitzgerald I'm not clear on what you're suggesting a standard library would look like. Are you envisioning a set of global functions provided by the runtime, or an implementation of the function in rockstar which can be imported, or something else?

**Comment by cwfitzgerald** [comment]
The distinction I was trying to make was between having a piece of syntax the compilers have to understand vs a standard library of some kind which is called using normal function syntax. I was thinking something on the order of `scala.PreDef` or python's built in functions. These are functions that form a standard library that is guaranteed to be there. They would consist useful math operations and any operations that would be better left to the compiler to implement.

To throw another idea into the pool we could do some combination of both, going the 'syntactic sugar` route, where some syntax is just an alias for calling the function with certain arguments.

**Comment by cwfitzgerald** [comment]
Along the same lines as this, it would be useful to create something similar to C++'s as-if rule to allow compilers a little lee-way as to what is a library function and what isn't, as well as allowing optimization of function calls and such.

**Comment by young-steveo** [comment]
I would prefer to not clutter the global scope with predefined words.  The more global words we add, the less expressive a user's lyrics can be without either overwriting the globals or digging through a thesaurus. I think it would be interesting to take the Go approach of providing a minimal language feature set and allowing the user to import predefined standard libs that accomplish math/string stuff. 

That said, we'd have to first figure out module/package/lib importing.

**Comment by cwfitzgerald** [comment]
I agree, I think having modules is the solution. Especially when you are defining stuff like `min` `max` it would be good to avoid the global scope conflict problem if we can.

There hasn't been a serious proposal for modules yet AFAIK, so if I have some time tonight I will write up something defining a spec for it and submit it as an issue for discussion. This also relates with #111, as scoping is important with modules.

**Comment by cwfitzgerald** [comment]
The standard library should definitely be called `the truck` or `the bus` or something like that

**Comment by kentros** [comment]
or `more cowbell`

**Comment by dylanbeattie** [comment]
Implemented in https://github.com/RockstarLang/rockstar/blob/main/spec.md#parsing-numbers-and-character-codes
