### ISSUE TITLE
Numeric literals - should `Limit is 100` work?

### ISSUE THREAD

**Issue by yyyyyyyan** [RockstarLang/rockstar#140]
I just got an [issue](https://github.com/yanorestes/rockstar-py/issues/20) on rockstar-py regarding this:
`Limit is 100` was being transpiled to `Limit = 0` (it was treated as a poetic number literal and, since there was no alphabetical character, it resulted to 0), instead of `Limit = 100`. 

The FizzBuzz minimalist example in the docs uses this syntax, but this is not described anywhere else in the specs. As of right now, I don't think it should work. What do you guys think?

**Comment by cwfitzgerald** [comment]
Very interesting. I think this is very tightly related to the ongoing discussion in #129. If we figure out an alternate syntax for `is` expressions with math, this is proper behavior, however, if we settle on having math expressions within `is` expressions, this should set limit equal to 100.
