### ISSUE TITLE
Add support for line breaks (line continuations)?

### ISSUE THREAD

**Issue by callumfrance** [RockstarLang/rockstar#142]
C-style languages use the `;` to say that this is where a statement ends, because in C-style, pretty much all white-space is arbitrary and optional - it's just a good convention.

It sort of looks like rockstar is going down the Python route where one line = one statement, however even python gives you the option to break up long lines using the ` \` thingy.

My proposal is that to be a bit like a piece of prose, rockstar could use ` -` (whitespace then hyphen) to break a line. Alternatively (and god forbid) if you break up an actual word, maybe a `-` (just a hyphen) could be used to line split, because this is how its done in English-style languages.

Take it to the top.

**Comment by young-steveo** [comment]
Maybe it should be the semi-colon?  A semi-colon at the end of a line could signify that the line is continued on the next line.  It's a bit more "prose" like.

**Comment by callumfrance** [comment]
My concern with semicolon is that it would have the exact opposite meaning that it has in most industry languages (i.e. confusing readability), and also that in prose you read a; hyphen as a line continuation - but if you just drop semicolons around you end up with; weird pauses.

**Comment by cwfitzgerald** [comment]
I agree with @callumfrance, I think we should stay away from the semi colon. I would be okay with the hyphen idea. 

Would it be possible to implement something that would implicitly continue a line? Or would that be too hard (too much ambiguity).

**Comment by callumfrance** [comment]
I think it would be too hard for a compiler to be able to tell. It would be a bit like reading a paragraph with no full stops.

**Comment by cwfitzgerald** [comment]
Fair enough, my vote remains for hyphen.

**Comment by sekullbe** [comment]
Combining with #77- maybe use 'Baby', 'Yeah', 'Oooh, and/or 'Whoa' as the line continuation marker at the beginning of a line. So, to steal a line from the idiomatic fizzbuzz implementation:

If Midnight taking my world, Fire is nothing and Midnight taking my world, Hate is nothing

becomes:
If Midnight taking my world,
Baby, fire is nothing,
Yeah, Midnight taking my world,
Whoa, Hate is nothing

That would also mean that by themselves they'd be a no-op, so you could just write "Yeah, baby, yeah yeah yeah" by itself and it would be meaningless filler, just like in real lyrics.

I'm torn on what to do in a poetic declaration. On one hand I don't want to take words away, but on the other, you could do something like this which would be cool:
My dreams were ice.
Yeah, A life unfulfilled; 
Baby, wakin' everybody up,
Oooh, taking booze and pills
