### ISSUE TITLE
Implement [chorus], [guitar solo], etc.

### ISSUE THREAD

**Issue by callumfrance** [RockstarLang/rockstar#143]
Something that I noticed in a lot of song lyrics is that songs are broken up into blocks with `[chorus]`, `[verse 1]`, `[guitar solo]`, `[intro]` all being labelled as such.

_Maybe this can be used to define functions?_

Not sure about passing parameters though...

Maybe you could add parameters onto the end?? e.g.
```
[chorus] (Rallying together now)
or
[chorus] (Johnny floors it, Ice cold conviction)
```

**Comment by Sifaus** [comment]
I think you can use "names" as parameters. Like who is singing this chorus? Something like:

```
[Chorus: Jamie]
Peter says Jamie
```

And multiple parameters can be split by a comma.

```
[Chorus: Jamie, Billy]
```

And naming different function can actually be done by adding numbers, or different names like you said.

```
[2nd Chorus: Jamie]
...

[3rd Chorus: Billy]
...

[Guitar Solo: Alice]
...
```

Than maybe we can call the functions by calling them out.

```
...
Alice enter (start?) the Guitar Solo!
```

**Comment by young-steveo** [comment]
We already have a function syntax.  Maybe this could be used as a goto label?

**Comment by cwfitzgerald** [comment]
@young-steveo I really don't like the idea of creating more goto's in the world, but if we must, we need to also define the semantics of variables when you jump into functions without actually calling them.

I'm personally for @Sifaus's idea.

**Comment by Malorn44** [comment]
Not sure if this is having any more work done on it but I think I like the syntax proposed by @Sifaus for functions more than the current one.
