### ISSUE TITLE
Can proper variables contain upper-case letters after the first one?

### ISSUE THREAD

**Issue by palfrey** [RockstarLang/rockstar#147]
Common variables are defined as only lower-case, and Proper variables are defined as having an uppercase letter for the beginning of each of their words, but doesn't say what valid characters for the rest of the word is. Some code out there (e.g. https://github.com/jzaia18/RockstarProjects/blob/master/tictacrock/tictactoe_nonidiomatic.rock) has proper variables with upper-case letters part way through variable names, and I'm not sure if it should be valid or not...

This is kinda a side-case as idiomatic rockstar shouldn't have upper-case letters in the middle of words because english words don't (AFAIK!) but non-idiomatic might.

**Comment by wizered67** [comment]
The spec says `Whilst some developers may use this feature to create variables with names like Customer ID, Tax Rate or Distance In KM...`, so seeing as it uses ID and KM as examples I'd say it's valid to have uppercase characters.
