### ISSUE TITLE
Keywords as variable names

### ISSUE THREAD

**Issue by wizered67** [RockstarLang/rockstar#148]
I'm curious to what extent keywords can be used as variable names. The spec says `Proper variables are proper nouns - any word that isn't a reserved keyword and starts with an uppercase letter.` That seems to answer the question for proper variables, but no mention is made for common variables which are described as `one of the keywords a, an, the, my or your followed by a unique variable name, which must contain only lowercase ASCII letters a-z.` Can the "unique variable name" for common variables be a keyword then?

**Comment by cwfitzgerald** [comment]
I'm going to argue that we shouldn't allow that. It would make things confusing and unnecessarily difficult. If others agree I'll roll it into #117 or #85

**Comment by wizered67** [comment]
Thinking about this a bit more though, I'm wondering how multi-word keywords should be handled. For example, "give back" is obviously a keyword, but are "give" and "back" both keywords also? My intuition says maybe they wouldn't be, since otherwise variable names are significantly more restricted given how many multi-word keywords are in the language. And a proper variable like `Give Back` wouldn't be allowed, but would a variable name like `Everyone Give Back` be allowed? Probably not since it directly contains a keyword?

Side note, right now the spec only says that proper variables can't be reserved keywords. I believe #117 should modify the spec to say "isn't a reserved keyword or literal word", assuming that variables names can't be literal words either (which seems like what we want since `True is false` is a bit confusing to say the least)

**Comment by cwfitzgerald** [comment]
I would say that `Give Back` and `Give` and `Back` are all reserved. This will simplify things. 

Could you add that as a comment on #117 so I can track it :)

**Comment by cwfitzgerald** [comment]
Where should this go, another PR, or should it be rolled it into a current one.

**Comment by wizered67** [comment]
I think it could just be thrown into #117, especially since that already has a section clarifying what a reserved keyword is. I'm not opposed to the idea of a new PR though if you'd prefer that.

**Comment by cwfitzgerald** [comment]
Alright, I'll pull that into #117. I'm trying to minimize the amount of PRs for dylan to go through.

**Comment by cwfitzgerald** [comment]
That is a fair argument. I was thinking about something like rockstar-py which does more blind conversion than actual compilation. I'm perfectly fine with having it only be a keyword if the whole thing is there. Holding off on adding to #117 until this is resolved.

**Comment by young-steveo** [comment]
I can't make my mind up on "my" either.
