### ISSUE TITLE
Proposal: Reference implementation

### ISSUE THREAD

**Issue by palfrey** [RockstarLang/rockstar#152]
Having just run into the fun of #130, I'm starting to think that Rockstar badly needs a reference implementation

Why do we need this?
----
Well, because writing a language spec is hard. Writing one that deals with all the ambiguities and is able to easily incorporate all the changes people have proposed without horrible clashes is even harder. There's a lot of good work here, but I suspect (based on mostly guesswork, plus some work with trying to run various programs out there through Maiden) there's a fair amount of deviation in what is "valid Rockstar", and checking that at the moment is very hard.

What would it be?
----
* Running code, in the main Rockstar spec repo
* Written with a priority on readability and maintainability. Ideally, in a language that at least most of the people that might write bits of spec could make changes to in parallel with proposed spec changes (which is why I'm not proposing [Maiden](https://github.com/palfrey/maiden), as Rust isn't everyone's cup of tea). Python possibly? Maybe start from the one in #27?
* Should be an interpreter/compiler, not a transpiler, to avoid clashes with the host language's opinion about how to do things like operator precedence
* A collection of "known good" Rockstar programs (README ones, various ones from community) along with their expected output and any required input (e.g. [see how I did this in Maiden](https://github.com/palfrey/maiden/tree/master/tests)) These should be run in CI (Travis/Circle probably) on changes. This could then also be used by other implementations as well to check their conformance.

What will it not be?
----
* The One True Interpreter. Features like making it run in a web browser should not be added. It's purely intended as a testing tool, and the wide collection of other implementations should continue to be encouraged 😄 
* The one place where all Rockstar programs go. The known good programs should not be used as a dumping ground for everyone's pet problem, but once the initial set is imported should only be expanded with language edge cases as we find them (and we might even want to remove longer example programs in favour of smaller examples that focus on one language area at a time).

Once this is done, any new language changes should be accompanied by test cases and changes to the reference implementation.

Thoughts?

**Comment by young-steveo** [comment]
Love this.  A really simple tree-walk interpreter could do the trick.

**Comment by dylanbeattie** [comment]
I completely agree - this is a great idea and will make it much easier to discuss and manage refinements to the language spec. And I agree that it should be an interpreter/compiler rather than a transpiler, so the implementation remains entirely responsible for details like operator precedence and variable scope. 

That said, I think a reference implementation that will run in a web browser might actually be a good thing, and so would strongly consider JavaScript as a language for the reference implementation. JavaScript is really widely supported and well understood, and there some great resources out there about using it to implement interpreters for other languages. I've been looking at http://lisperator.net/pltut/ - although the computed output is also JS, it's a full lexer/parser that creates an AST and then separately generates JavaScript code based on that AST, rather than a transpiler, which also creates possibilities for doing some very cool things with (for example) rendering the AST using SVG in-browser as well.

Thoughts?

**Comment by cwfitzgerald** [comment]
I mean, quite frankly, that was my goal with the webpiler. Have a full blown recursive decent parser that is strict to the standard and can easily share links between people. I also understand that I screwed myself over by implementing it in scala.js as scala isn't a very well known language, though it would've never happened if it was in a language that didn't have great parser-combinator libraries. I have been stuck on doing proper IR/Codegen for a while now, but it wouldn't be crazy to be able to get a full tree-walking interpreter within the next day or two. Everything is there except actually doing it.

**Comment by dylanbeattie** [comment]
OK, some decisions distilled from the Discord chat about this:

We want to create a reference implementation that gives us a more disciplined way to evolve the language spec, but also as a useful resource for students of programming language design or people who are curious about how a compiler actually works.

We've chosen Python as an implementation language - it's widely understood, popular, runs everywhere, and has fewer idiosyncrasies than JavaScript. The plan is to create a reference implementation of a subset of the Rockstar language first, and then use the process of iterating on that implementation to support additional features as a way to validate the development and collaboration process.

Discussion is happening on Discord, where there's a Rockstar Developers server running with many of the core contributors in it. Join us: https://discord.gg/A48XRUd

**Comment by palfrey** [comment]
I think this is basically done now with Satriani, so closing
