### ISSUE TITLE
Proposal: Bollocks.

### ISSUE THREAD

**Issue by dylanbeattie** [RockstarLang/rockstar#169]
Rockstar needs a mechanism for handling runtime errors, such as division by zero.

I propose the following:

* We add a new keyword to the language, `bollocks` (with the alias `nonsense` for those of a delicate sensibility)
* Any operation that would cause a runtime error returns `bollocks`
* If any operation returns `bollocks`, the program will halt immediately with an error message

HOWEVER

If you want to continue execution following a runtime error, you must start your program with the line:

```
Never mind the bollocks
```

This has a broadly similar effect to the infamous [`On Error Resume Next` in VBScript](https://stackoverflow.com/questions/2202869/what-does-the-on-error-resume-next-statement-do), and allows you to write Rockstar code that works like this:

```
Never mind the bollocks

A kiss is crying, 
The water is splintered

My love is a kiss over the water
If my love is bollocks
Shout "the water was zero!"
Else
Shout my love
```

(This borrows heavily from the idea of Signalling NaNs and Quiet NaNs as specified [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754))

**Comment by cwfitzgerald** [comment]
Pure bollocks, love it!

**Comment by callumfrance** [comment]
I like it but it's very British lol.

Maybe if this system allowed the capability to handle more than one type of runtime error we could make exception handling more expressive.

**Comment by FurkanKambay** [comment]
Talking about exceptions, I think "Throw up" should be a thing.
