### ISSUE TITLE
Test case for if/while/function exits

### ISSUE THREAD

**Issue by palfrey** [RockstarLang/rockstar#175]
I had a bug in Maiden regarding the following program
```
if false
say "bar"
else
while true
say "foo"

```

Ignore for a moment that it's an infinite loop, as the bug was in the parsing. So, correct interpretation of the newline after `say "foo"` would be to exit the while loop. However, my implementation (prior to https://github.com/palfrey/maiden/pull/14 which fixes this) interpreted newlines as "exit any if, then any while, then any function", so it tried to exit the if first, then the while loop.

I've got my own test case that checks my parser output, but haven't yet figured out how to write a test case that can be added to the reference implementation.

**Comment by palfrey** [comment]
I will also note that my reasoning on why the test needs adding is that Maiden passes the entire current test suite, yet had this bug.

**Comment by cwfitzgerald** [comment]
This has to be the only save behavior for programs, so I'd be happy to accept a PR with these tests from maiden, or next time I work on rockstar I'll add some tests.

**Comment by palfrey** [comment]
Problem is the maiden test is "does this exact Rust structure from the parser output match what the parser output", so it's not exactly portable :(
