### ISSUE TITLE
Can object literals use poetic literals unless quoted?

### ISSUE THREAD

**Issue by AncientSwordRage** [RockstarLang/rockstar#180]
It feels more consistent to need to do:

`Something with 1 for the "money", 2 for the "show", 3 to get "ready", and 4 to "go"`

To get `{1: "money", 2: "show", 3: "ready", 4: "go"}`.

Unless I've misunderstood the proposed documentation, without quotes variable assignment with poetic literals should give:

`{1: 5, 2: 4, 3: 5, 4: 2}`

**Comment by cwfitzgerald** [comment]
Object literals at this point basically don't exist. Yes they are in the documentation, but the format is still basically undecided :) If you want we can discuss more on the discord :)
