### ISSUE TITLE
Alias for Put X into Y : Let Y become X

### ISSUE THREAD

**Issue by gaborsch** [RockstarLang/rockstar#186]
I'd recommend to have a new alias for the `Put ... into ...` assignment operation. 

Since assignment is the most common statement int programs, it becomes quite boring reading "Put ... into ...". Therefore I think it would help a lot if we had more options to express the same.

My proposal is the `Let <variable> become <expression>` assignment operation. Also, if it does not conflict with other plans, it could be shortened to `Let <variable> be <expression>`

It is important, that the order of operands is the opposite as the `Put into` operation, but the `Let become` complies with the traditional programming languages: first comes the variable, second comes the expression. Also, the poetic assignment is using this order (varable, literal)

Some examples:
`Let your dreams become true` (your dreams := boolean true)
`Let  the message be "Hello San Francisco"` (the message := "Hello San Francisco")
`Let Tommy be nothing`
`Let Our Love become Infinite taking my love and your love`

**Comment by dylanbeattie** [comment]
I really like 

```
let X be y
```

as an assignment syntax. In fact, I wish I'd used that in the first place - much cleaner and easier to use in lyrics. We'll add it once the reference implementation is stable.
