### ISSUE TITLE
If / Else block syntax

### ISSUE THREAD

**Issue by gaborsch** [RockstarLang/rockstar#190]
I need some clarification. Can someone tell me what is the proper use of the `if - else` structure? I can find neither an explicit description in the language specs, nor any example code that should guide.

The question is: Shall we put an empty line before the `Else` statement, or not?

**Pro** (we should have a line):
According to the [Rockstar Webpiler](https://rs.cwfitz.com/daW8KrXkryM), there is an empty line after the IF block. If I remove it, the transpiler signs a parse error:
```
Factorial takes X
if X is nothing
Give back 1 (THERE IS THE EMPTY LINE AFTER IF BLOCK  ------>)

else 
put X minus 1 into NewX
Give back X times Factorial taking NewX
(end if)
(end func)
```

In addition, the Specs says about "subsequent block" after the conditional expression, and (regarding Bolcks) it says that "a block (...)  is terminated by a blank line or the end-of-file. ". Also, the Specs mentions the "code block following the Else keyword" - meaning that Else should have its own block.

**Against** (we should have no newline)
There is a test case, namely the  [ELSE outside of IF test case](https://github.com/dylanbeattie/rockstar/blob/reference-implementation/tests/parse-errors/elseOutsideIf.rock), that explicitely says that this syntax must produce a compile error.

The Specs also does not mention that an explicite empty line must be put after the IF statement, before the else, rather it says "Optionally, an Else block can be written after an If block" - if we interpret the ELSE line as a termination of the IF block, this all could stay valid.

**Comment by cwfitzgerald** [comment]
This is a bug in the webpiler that I know about. You shouldn't have a line there. I thought i fixed it but I might not have pushed the changes,

**Comment by dylanbeattie** [comment]
`else` should definitely terminate a block - it's only actually valid inside block scope anyway, since if you're not inside an `if` block it isn't always clear which `else` you're referring to.

```
If X is nothing
If Y is nothing
Say "both X and Y are nothing"

Else
Say 'X was not nothing'
```

compared with:

```
If X is nothing
If Y is nothing
Say "Both X and Y were nothing to me, oh, Vienna."
Else
Say "Y was really something, baby!"
Else
Say "X was really something, baby!"
```

Whether this is supported by any of the current interpreters is an open question, but I'll make sure it's covered in the spec and the reference implementation.

**Comment by gaborsch** [comment]
Thanks, @dylanbeattie I suspected that Else must terminate an If block, but that's clear now.
