### ISSUE TITLE
Idiomatic FizzBuzz example errors

### ISSUE THREAD

**Issue by ascheja** [RockstarLang/rockstar#191]
I think I've found two problems with the [idiomatic FizzBuzz example](https://github.com/dylanbeattie/rockstar/blob/reference-implementation/tests/correct/fizzbuzz-idiomatic.rock)

1. There are two blank lines (lines 6 and 7), but we only need one to terminate the function block right?
2. `My World` is initialized as `nothing` (== `null`) in line 9 and `Build ... up` (incremented) in line 13, but the spec explicitly mentions that using the increment/decrement operators on `null` is an error: `<op> Null => Error`

**Comment by dylanbeattie** [comment]
Hey,

1 - yes, we only need one. The second one isn't actually a problem - it should be ignored - but you're correct that it isn't necessary.

2. Correct - but I think the spec is wrong here; build up & knock down nothing is useful from a lyrical perspective and very easy to support.

I'll get it fixed for 1.0 :)
