### ISSUE TITLE
Pronouns in satriani

### ISSUE THREAD

**Issue by ascheja** [RockstarLang/rockstar#198]
Just tried the satriani interpreter on the homepage, I think I've found a problem in the implementation of `99 bottles of beer` example, lines 5 to 7:
```
...
While the beers ain't nothing
Say it with your heart
Say it with your soul
...
```
The first `it` in line 6 clearly refers to `the beers`, but the second `it` should refer to `your heart`, but satriani seems to keep the reference to `the beers`. So is this my misunderstanding or a bug both in satriani as well as in the `99 bottles of beer` implementation?

**Comment by minirop** [comment]
I would guess that `expression` at not taken into account for `it` because it would break when the variable is before `it`.
```
While the beers ain't nothing
Say your heart with it
```
would be equivalent to:
```
Say your heart with your heart
```

**Comment by dylanbeattie** [comment]
You're right, there's a discrepancy here. Satriani only [updates the pronoun alias during an assignment](https://github.com/RockstarLang/rockstar/blob/master/satriani/satriani.interpreter.js#L105) - so in the `99 bottles of beer` example, it's actually the line

```
The beers were numbering fa'too'many
```

that causes pronouns to resolve to `the_beers` - and it'll stay like that until there's another assignment.

This was sufficient to pass all the tests in the suite, and also allowed the `99 beers` example to use that `say it with your heart` syntax which I really liked - but you're right, it deviates from what's actually in the spec.

So it's technically a bug in both beers and Satriani, but a bug that I plan to promote into a feature and update the spec as soon as I've worked out exactly how it *should* behave to support the sort of colloquial English phrases like the ones in the `99 beers` example.

**Comment by dylanbeattie** [comment]
Spec updated to specify that pronouns refer to the most recently **assigned** variable.
