### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by gaborsch** [RockstarLang/rockstar#204]
Here's my original proposal I made for Rockstar arrays we discussed on Discord, please have a look, comments are welcome!

# Rockstar Arrays

There are two kinds of array in Rockstar: list (containing scalar values or other arrays) and associative array (containing key-value pairs, where keys are scalars and values are scalar values or other arrays). An array can be of either type, but mix of the two kinds is not possible. 
The constant literal `empty` will represent an empty array for both kinds of arrays. (Empty was an alias for `null` so far, it is a breaking change, but to preserve at least the comparison, it will be equal to `null`)

## Lists
Indexing of a list always starts with zero, if any element added or deleted, the indexes are shifting.

### Poetic array initialization
Poetic array initialization is the extension of the current poetic literal initialization, by using the `containing` keyword after `is`/`was`/`are`/`were`. As an alternative, we introduce an array-specific poetic assignment, with keywords `hold`, `holds`, `contain` and `contains`.
Other possible aliases: `Within <list> is/was/are/were <value> [, <value> ...]`
```
<variable-ref> is/was/are/were containing <variable-or-literal> [and <variable-or-literal> ...]
<variable-ref> is/was/are/were empty 
<variable> contains <values>
```
The literal `empty` is a constant literal for an empty list.

[[`containing` has 10 letters, in poetic assignment it resulted `0` digit so far, it is very unlikely to have happened in any code.]]

### Dereferencing
Dereferencing a list is done by `at` and `around` keywords following a numeric expression, that defines the index. 
```
<variable-name> at/around <expression>
```
If the value is not found (because of under- or overindexing), it evaluates to `mysterious`.

It is not possible to use two-level deep dereferencing for a variable, because the second dereference will be interpreted as the part of the index expression. For example, 
`	Dwarves around the house at the woods`
would first evaluate `the house at the woods`, and use its value to index `Dwarves`.

### Truthiness
The empty list is falsy, the non-empty is truthy. This can be used for emptiness check operation.

### Equals
An empty list equals to `null`. A list equals to another list if they contain the same indexes, and at each index they contain equal values. Also,an  empty list is equal to an empty assoc-arrays. Otherwise it is non-equal.

#### Size
The size of an array should be determined by the unary `count of` (or `length of`, `height of`) operator, it will return the number of elements in the list. `null` and `mysterious` values are treated as empty list.
```
count of <list>
```
#### Sort
Sort a list. Creates a new list for the values, in sorted order. Sorting is determined by `<` `>` operators of the values. For values other than strings and numerics, the result is indeterministic. 
```
sorted <list>
<list> sorted
```
The `sorted` keyword binds the expression more tightly than other array operations (e.g.slicing and peeking)

#### Slicing
Slicing lists is possible in 3 flavors: cutting head, tail or both, The function keywords are `from` and `till`, respectively, combining them is also possible. The list is unmodified.
```
<list> from <index-expr>
<list> till <index-expr>
<list> from <index-expr> till <index-expr>
```

#### Peek
Peek at the last element of the list, returning its value. If the list is empty, returns `mysterious`. The list is unmodified.
```
last of <list>
```
#### Append/prepend
Append an element, creates a new list:
```
<list> plus <expression>
```
Prepend an element, creates a new list:
```
<expression> plus <list>
```

#### Concatenate
Concatenate lists, creates a new list:
```
<list> plus <list2>
```

#### Remove an element by index
Remove an element from the list, creates a new list. The index is taken as  numeric value.
```
<list> minus <index-expression>
```

#### Set an element by index

Set value for a specified index of a list will use the dereference syntax. Setting a not-`null` value will set or overwrite the specified index (if overindexed, it will be appended as the last element), setting to `null` or `mysterious` value will remove the list element, shrinking the list.
```
Put <expression> into <variable-name> at/around <expression> 
```

#### Iterate through a list 
Iteration works the same like a `While`-loop, but the list should not be modified within the loop (expect uncertain behavior otherwise). Alias for `as` could be `alike`.
```
While <list> as <value-variable-name>
While <list> as <value-variable-name> for <index-variable-name>
```
After entering the loop, `it` refers to the last value-variable. Iterating through a list with `for` keyword puts the array index into the key variable.

#### Stack operation (push/pull)
Append an element to the end of the list, modifying it.
```
Push <value> into <list>
```
Remove the last element from the array, modifying it. Also assigns the removed value to the variable (`it` should refer to this variable after this statement) 
```
Pull <variable> from <list> 
```

##  Associative Array
For marking associations we always use the `value for key` syntax.

### Poetic array initialization
Poetic array initialization is the extension of the current poetic literal initialization, by using the `containing` keyword after `is`/`was`/`are`/`were`. As an alternative, we introduce an array-specific poetic assignment, with keywords `hold`, `holds`, `contain` and `contains`.
```
<variable> contains <values>
<variable-ref> is/was/are/were containing <variable-or-literal> for <variable-or-literal> [and <variable-or-literal> for <variable-or-literal> ...] 
<variable-ref> is/was/are/were empty 
```
`empty` value is considered an empty assoc-array in array operations.

### Dereferencing
Dereferencing an associative array comes with the `for` keyword, following the key expression.
```
<variable-name> for <expression> 
```
If the value is not found (e.g. there is no such key), it evaluates to `mysterious`. It is not possible to use two-level deep dereferencing for one variable.

### Truthiness

The empty assoc-array is falsy, the non-empty is truthy. This can be used for emptiness check operation.

### Equals
An empty array equals to `null`. An assoc-array equals to another assoc-array if they contain the same keys, and for each key they contain equal values. Also, an empty assoc-array is equal to an empty list. Otherwise it is non-equal.

#### Size
The size of an array should be determined by the unary `count of` (or `length of`, `height of`) operator, it will return the number of elements in the list or assoc-array.
`null` and `mysterious` values are treated as empty array.
```
count of <assoc-array>
```

#### Keys
Get the keys of the associative array. creating a new list for the values, in indefinite order. `null` and `mysterious` values are treated as empty array.
```
all keys of <assoc-array>
```

#### Values
Get the values of the associative array. creating a new list for the values, in indefinite order. 
`null` and `mysterious` values are treated as empty array.
```
all values of <assoc-array>
```

#### Merge
Merge arrays, creating a new array:
```
<assoc-array> plus <assoc-array2>
```

#### Remove an element by key
Remove a key-value pair from the array, creating a new array. 
```
<assoc-array> minus <key-expression>
```

#### Remove a subset
Remove key-value pairs from an array, creating a new array. Creates a new array , where the keys of the second array will be removed from the first array.
```
<assoc-array> minus <assoc-array2>
```
Remove key-value pairs from an array, creating a new array. The values of the second array will be used as keys to remove elements from the first array
```
<assoc-array> minus <list>
```

#### Set an element by key
Set value for a specified key of an associative array  will use the dereference syntax. Setting a not-`null` value will set or overwrite the specified key, setting `null` or `mysterious` value will remove the key-value pair.
```
Put <expression> into <variable-name> for <expression> 
```

#### Iterate through an array 
Iteration works the same like a `While`-loop, but the array should not be modified within the loop (expect uncertain behavior otherwise). Alias for `as` could be `alike`.
```
While <assoc-array> as <value-variable-name> for <key-variable-name>
While <assoc-array> as <key-variable-name>
```

After entering the loop, `it` refers to the last value-variable, if given (otherwise refers to the last key).
Iterating through an assoc-array without specifying `for` keyword iterates on the keys of the assoc-array (using keys we can fetch the value).

#### Add/remove elements by key
Add an element to the array, modifying it.
```
Push <value> for <key> into <assoc-array>
```

Remove a random element from the array, modifying it (preferably the first key). Also assigns the removed key-value pair to the variables 
```
Pull <value-variable> for <key-variable> from <assoc-array> 
```

# Examples
## Roses
```
the roses were containing "red", "purple" and "white"
While the roses alike my rose
Say "A " with my rose with " rose for my darling"
(end while)
```

## The band
```
the members were containing "Johnny" for "guitars", "Jack" for "keyboard", "Jake" for "drums" and "Jamie" for "singer"
While the members alike the man for the role
	Say "The awesome man for " with the role plus " is " with the man
(end while)
```

**Comment by gaborsch** [comment]
To summarize the Discord channel:
* `for` is considered a good shot for associative arrays (`one for the money, two for the show`, and also `Money for nothing and your chicks for free`)
* `at` is on the right track, but needs something extra (perhaps an alias like `in` or `on`)
* Other syntaxes proposed for array initialisation:
`Within the elements are the foo, the bar, the baz`
`Your dreams hold the key, the fire, the future` (this one was agreed on, so I included into the spec)
* Dylan had an idea to use `rock` and `roll` as aliases for `push` and `pop` (didn't talk about it too much, but I like the idea)
* Dylan propsed to use a minimal set of functions (so, the above may be too much)
* Also we talked about modifying statements vs non-modifying expressions, with no conclusion.

**Comment by ascheja** [comment]
Regarding
```
In operations, `null` or `mysterious` may represent the empty array, for both kinds
```
- `mysterious` is defined to be not equal to anything but itself, but here it would be equal to an empty array?
- What is the result of `Some List plus nothing`?
  1. `nothing` is treated as empty list -> concat, result is equal to `Some List`
  2. `nothing` is treated as value -> append, `null` appended as last element to `Some List`
  3. Something else?

**Comment by gaborsch** [comment]
@ascheja Good points, both.

Regarding `mysterious`,  we can take it out of the equals list (I already edited the proposal in accordance with it)

Regarding `null`, we already have `empty` as an alias for `null`, which should be interpreted as an empty list
`Some List is empty` - a perfect empty list initializer.

IMHO **we need an empty array constant**, that would solve the problem. `empty` is a perfect candidate for it, and it would be nice if we could use it both for lists and assoc-arrays. `null` could be treated as a value (as you wrote in ii. option)

Reusing `empty` would be a breaking change, we could consider using some other keyword - IMHO it is the so natural that may worth it.

Some other examples to consider (I put the expected result in comment, [] means list):
```
My list is empty 
Say my list (empty)

My emptylist contains "Tommy"
Let my emptylist be my emptylist minus "Tommy" 
Say my emptylist (empty)

Say my list plus nothing ([null] -- one element whose value is `null`)
Say nothing plus my list ([null] -- one element whose value is `null`)
Say nothing plus nothing (null)
Say my emptylist plus nothing ([null] -- one element whose value is `null`)
Say my emptylist plus my emptylist (empty)
Say nothing plus my list ([null] -- one element whose value is `null`)
Say my list is empty (true)
Say my list is null (true -- it is just for the equals)
Say my emptylist is empty (true)
Say my emptylist is null (true -- it is just for the equals)
Say my list is my emptylist (true)
```

**Comment by ascheja** [comment]
@gaborsch 

What about using `void` as a new keyword for an empty list? But even if, what happens if I would initialize a variable to an empty array with `Tommy is void`. Now should `Tommy` be treated as a list or as an empty array?

**Comment by gaborsch** [comment]
It could be both list and assoc array, because there's not much difference. If you add a value to it, it's a list, if you put a value into it for a key, it's an assoc array.
 
Let's say we will implement it as an empty list. All operations will work: size is 0, keyset is empty, iterating will have 0 cycles, etc.
The only thing we should consider is when we put a value into it, then we need to morph it into an assoc array.

But from the user perspective it does not matter. `void` or `empty` or whatever we define will mean an empty list and an empty assoc array, whatever he wants to do with it.

**Comment by gaborsch** [comment]
Void is good, actually, I like it, but I'm a bit sorry for `empty`...

**Comment by gaborsch** [comment]
I found another good alias: `hollow` - it sounds quite good to me.

**Comment by chrispepper1989** [comment]
Did this get fully implemented? count of doesnt seem to be working for me?

**Comment by gaborsch** [comment]
No, check the spec for the implemented array handling.

**Comment by chrispepper1989** [comment]
ah, has there been anything added that lets you loop through a string or get the scalar value of either an array or string length into a variable? 

Here is what I've tried: 

```
        Listen to your heart    
        cut your heart into Pieces
        Shout Pieces
        Jo is count of Pieces  (so i know this doesnt work re spec)
        Chris is Pieces
        shout Jo
        shout Chris 
        Jo is Chris
        while Jo aint nothing 
         shout Pieces at Jo without 1
         knock Jo down

```
If I use "Hello World" as the input this the output i get:

  ```
  11
    526
    6
    o
    l
    l
    e
    H
    ...

```
Even though "shout pieces" comes out a the correct number "11" I cant seem to inject that scalar value into a variable

Any suggestions?

**Comment by ysthakur** [comment]
Has there been any progress on this? I love this proposal but the stuff mentioned here still isn't working. Is there a version of rockstar other than the online Satriani interpreter that supports this?

**Comment by gaborsch** [comment]
Rocky has an unofficial support for it, check the programs/tests/fixtures/arrays for an example.

**Comment by gaborsch** [comment]
@ysthakur Well, I've double checked, and it seems that the previously implemented features were gone when I implemented the new standard Rockstar array, because they conflicted with the new spec. Some operations work, but many don't, some have different semantics. However, implementing a while ... alike ... loop should not be a big deal.

**Comment by ysthakur** [comment]
@gaborsch Oh, that’s too bad. I suppose one could always modify a Rockstar compiler or interpreter to do that, as you said. Thanks for the quick replies!

**Comment by gaborsch** [comment]
@ysthakur you are welcome to modify Rocky, if you know Java. Feel free to clone and to create a Pull Request if you want to. You can also create a PR to Satriani - but since Satriani is the reference implementation, it will only be incorporated if it becomes a language feature.

**Comment by ysthakur** [comment]
@gaborsch Rocky sounds interesting, I will definitely look into it and try contributing.

**Comment by dylanbeattie** [comment]
Array spec: https://github.com/RockstarLang/rockstar/blob/main/spec.md#arrays
