### ISSUE TITLE
new string equality tests?

### ISSUE THREAD

**Issue by marcinruszkiewicz** [RockstarLang/rockstar#207]
Are they correct?

I was updating the Kaiser-Ruby implementation with the new test suite and encountered this.

Spec says `String <op> Boolean => Convert the string to a boolean using all defined aliases.`, however the new test suite has tests like these:

`say "lies" is false` => `false`
`say "lies" is true` => `true`

Which treat every string as truthy no matter what it contains.

Both my implementation and Maiden's online version convert the aliases, so the string can actually have a value and still be falsy for comparisons.

So, which behaviour is correct here?

**Comment by gaborsch** [comment]
Yeah, I've also hit this issue when implementing my Java interpreter. I've decided to comply with the tests, but the spec needs to be updated, if the tests are correct.

**Comment by marcinruszkiewicz** [comment]
Interestingly enough, the old reference tests for this were different: https://github.com/RockstarLang/rockstar/blob/reference-implementation/tests/correct/operators/equalityComparison.rock#L33 and https://github.com/RockstarLang/rockstar/blob/reference-implementation/tests/correct/operators/equalityComparison.rock.out#L33

**Comment by dylanbeattie** [comment]
Yes, the tests are correct, the spec is out of date (and the older version of the test suite reflected the old behaviour)

The thinking behind this is that a string such as `"lies"` evaluating as false could lead to some weird behaviour when support is implemented for string manipulation. For example - popping the leading character off a string until the string is false; if you started with `"assemblies"` or `"multiplies"` you'd get the false condition when the string wasn't actually empty.

`"lies" > false` would be better support by explicit parsing than implicit type coercion.
