### ISSUE TITLE
Quine (arrayless)

### ISSUE THREAD

**Issue by hapaxlego** [RockstarLang/rockstar#218]
I seem to have written a [rockstar quine](https://github.com/hapaxlego/rock_wine) (probably the first one that doesn't use arrays). To be honest roskstar is not my first programming language or the one I'm most familiar with, so I wanted some more experienced programmers to check it and have some fun before adding it to Rosetta.
The minimalistic version should be almost readable, the idiomatic adds some poetic numeral literals and a workaround for a misleading joke. I guess the trailing spaces and comments handling could lead to some problems. I had some trouble with uppercase It (seems expected behavior) and replaced an If/Else inside a function with two Ifs to make it work on both rocky and the website (probably related to #190). Feel free to add it to the examples. Sorry for all the edits, hope this didn't cause too much trouble.

**Comment by dylanbeattie** [comment]
Added to rockstar/examples: https://github.com/RockstarLang/rockstar/commit/4383edfd5c80704cf0eec8b45ecbda1715a66eab
