### ISSUE TITLE
Code Java like Rockstar

### ISSUE THREAD

**Issue by LivelyCarpet87** [RockstarLang/rockstar#227]
I recently created a Java Package that could make Java read more like Rockstar using objects. I am unsure if this counts as a contribution. 

eg. 
Tommy.is_("Nothing");
while(Tommy.isnt(Eve) {
    I.build(Tommy, "up again");
}
I.scream(Tommy);

more at https://github.com/LivelyCarpet87/JavaLikeRockstar

**Comment by dylanbeattie** [comment]
This is cool :) I've added a new section to https://codewithrockstar.com/code including links to this and a few other Rockstar-inspired projects.
