### ISSUE TITLE
Can we get a collection function within rockstar.

### ISSUE THREAD

**Issue by hopppz** [RockstarLang/rockstar#228]
I couldn't see any kind of data collection like lists or array.

could we possibly get those added to rockstar?

**Comment by dylanbeattie** [comment]
You doing Advent of Code too? :)

I have a draft implementation of arrays that should be live later today - will share the PR when it’s ready to look at.

**Comment by gaborsch** [comment]
I also have a 99% ready [proposal of Object Oriented Programming](https://github.com/gaborsch/rocky/blob/master/OOP.md) in Rockstar, where I implemented a list and and array in Rockstar OOP. It only works in Rocky, though.

**Comment by hopppz** [comment]
@dylanbeattie do you maintain any of the compilers for rockstar?

I used the python one just because It's my go to language but I guess I'd also have to wait for the compiler to be updated to pick up your changes.

**Comment by dylanbeattie** [comment]
Yeah - Satriani, the JS interpreter that's running at https://codewithrockstar.com/online/, is mine - any changes and new features will be pushed there first, and I tend to regard Satriani as the 'reference implementation' for new features.

https://github.com/RockstarLang/rockstar/tree/master/satriani

**Comment by dylanbeattie** [comment]
So, um, yeah. Rockstar's supported arrays for about a year now. I just completely dropped the ball when it came to keeping on top of issues. Blame 2020. :)
