### ISSUE TITLE
The spec should say only scalar values can be passed to functions

### ISSUE THREAD

**Issue by jerryjeremiah** [RockstarLang/rockstar#244]
The spec says:

> Arguments may only be variables or literals. Compound expressions are not allowed.

And

> Returning an array in a scalar context will return the current length of the array:

It doesn't say that functions only accept scalar variables so I expected that I could pass an array to a function.

So I tried this at https://codewithrockstar.com/online

    the function takes array
    shout "The parameters that were passed: "
    shout array at 0
    shout array at 1
    shout array

    let param at 0 be 3
    let param at 1 be 4
    shout "The parameters to be passed: "
    shout param at 0
    shout param at 1
    shout param
    the function taking param

But it passes the length of the param to the function instead of the array and then doesn't complain when I try to index it.

Should passing arrays be allowed or should the spec be more specific about the fact that only scalar values can be passed to functions?

**Comment by dylanbeattie** [comment]
This is fixed in the latest release; arrays can now be passed as parameters to functions. Arrays are passed by value as shallow copies.
