### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by hapaxlego** [RockstarLang/rockstar#249]
I open this issue to see if anybody thinks there is a need for a common alias issue, either because it makes sense to consider some of them in conjuction or to make the proposals and/or issues in general easier to scroll. I also thought that adding local aliases with a "means" keyword or something similar would be a great idea, because different people have different definitions of "rock", even if used with a disclaimer, since guaranteeing that it would always work as expected seems harder to implement.

@jerryjeremiah I don't think there's anything wrong with everybody imlementing their own aliases and sharing them and want to make clear that I didn't have anything against your proposal and apologize if my comments were badly perceived, since opening a new issue was probaby a better course of action and looking mean on the internet is easier than I think.

**Comment by gaborsch** [comment]
I think it's a good idea, but we need to elaborate the syntax a bit. I was just about to prepare Rocky to support this kind of aliasing
