### ISSUE TITLE
Are there any plans to add Rockstar to Linguist?

### ISSUE THREAD

**Issue by johansenja** [RockstarLang/rockstar#251]
Are there any existing plans to add Rockstar to [linguist](https://github.com/github/linguist)?

(I couldn't see it in https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)

It's important for people to be able to see that you are a legit Rockstar developer 😎🤘🏻 (asking for a friend)

**Comment by dylanbeattie** [comment]
This would be awesome, but isn't something I'm likely to look at myself any time soon.

**Comment by Nixinova** [comment]
Open an issue in github/linguist to request an addition, it just needs 200+ repos using it.
