### ISSUE TITLE
All satriani tests fail with the same error

### ISSUE THREAD

**Issue by Tyrannas** [RockstarLang/rockstar#258]
While trying to run the tests i get the same error for each test:

` SyntaxError: Expected "&", "'n'", "(", "*", "+", ", and", ",", "-", "/", "\n", "between ", "minus ", "of ", "over ", "plus ", "times ", "with ", "without ", [ \t], or [;,?!&.] but "\r" found.`

And when I try to run my own code using satriani i get the exact same error.

**Comment by dylanbeattie** [comment]
Ooh. Looks like a Windows line ending bug - amazed that nobody’s seen it before. I’ll get it fixed, but in the meantime saving your files with Unix-style line endings (\n instead of \r\n) might fix it...

**Comment by dylanbeattie** [comment]
Yep. Looks like up until now all Rockstar developers have been using macOS or Linux. :)

I've updated the parser and tests so they'll work on Windows as well as mac/Linux.
