### ISSUE TITLE
Chorus as macro?

### ISSUE THREAD

**Issue by simcop2387** [RockstarLang/rockstar#28]
A lot of languages add metaprogramming via macros to generate more code at compile-time.  It might be useful to add something like this to the language to easily repeat a lot of similar code, but changing things inside it.  I.e. change which variable something is assigned to after a wordy calculation.

It might also make more sense to add choruses instead as a simple anonymous function you can repeatedly call (until the next chorus is defined).

**Comment by dylanbeattie** [comment]
I'm looking through all the outstanding issues to see which ones we should consider for Rockstar 2.0, and I don't think macros is one of them. Sorry.
