### ISSUE TITLE
How to work with "slash" characters

### ISSUE THREAD

**Issue by Rabadash8820** [RockstarLang/rockstar#284]
I don't see anything in the spec about working with "slash" characters like `\n` and `\t` for newlines and tabs, resp. How does one create a string expression with newlines or tabs, e.g. for I/O? Neither `put str plus "\n" into str` nor `shout "\n"` work as expected, appending/printing the verbatim characters `\` and `n` rather than a newline. The story is similar for `\t`.

**Comment by JapanYoshi** [comment]
At this moment, the most reliable way to get a newline or tab is to `cast` an integer.
