### ISSUE TITLE
Rounds = sub routines/threads

### ISSUE THREAD

**Issue by jaysonesmith** [RockstarLang/rockstar#30]
Just adding an idea to call threads, subroutines, etc as rounds

**Comment by tautology0** [comment]
You often get simultaneous lyrics in tracks placed in  ( ), so for an async thread, the below would make sense:

```
(while Tommy ain't nothing shout Hello
knock Tommy down)
Listen to the audience
Yell it!
```

**Comment by jaysonesmith** [comment]
Ah, yeah, that's fair enough! Good thinking :)

**Comment by jaysonesmith** [comment]
That definitely seems like a much more idiomatic Rockstar way.

**Comment by dylanbeattie** [comment]
There are no plans to add threading or parallel execution to Rockstar.
