### ISSUE TITLE
Can I get length of array as a value?

### ISSUE THREAD

**Issue by weshinsley** [RockstarLang/rockstar#300]
Is there a way of getting the length of an array into a variable I can work with?
For example:-

```
rock my array with 1, 2, 3
let your love be my array
whisper your love
knock your love down
whisper your love

```

prints 
```
3
NaN
```

So `your love` when printed gives the length of the array, but when used in a calculation I guess is a pointer that doesn't get knocked down in the way I'd like. I think what I'm really asking is for a syntax like 

```
how deep is your love
```

**Comment by gaborsch** [comment]
Evaluate your array in a scalar context. For example:
```
rock x with 1, 2, 3
let y be 0 with x
let z be x without 1
say y
say z
```

**Comment by weshinsley** [comment]
Got it. Thank you!

I am having a go at some Advent of Code 2021, but it's early days. My style is rather eclectic so far, but I'm learning...

https://github.com/weshinsley/advent-of-code/tree/master/2021/Rockstar
