### ISSUE TITLE
"has" as alias for "is"

### ISSUE THREAD

**Issue by Narnillian** [RockstarLang/rockstar#303]
When declaring an integer, the following code works:
`my love is greater than the sun`
This does not work:
`my love has a giant yearning`

`has` should be an alias for `is`

**Comment by JapanYoshi** [comment]
I disagree. “Has” is a different word from “is”, and should be reserved for checking if an array contains an element or something.

**Comment by JapanYoshi** [comment]
Related to this array membership idea, I think it would be clever to distinguish “has” vs. “(has) got”.

For example,

    If your love has thorns

could check if the array `your_love` contains the value of the variable `thorns`,

    If your love has got thorns

could check if it contains the number 6.
