### ISSUE TITLE
Add rockstar to https://www.99-bottles-of-beer.net/

### ISSUE THREAD

**Issue by athomschke** [RockstarLang/rockstar#309]
I just sent a friend a link to 99 bootles of beer and told her 'hold on, let me link you to my favorite programming language' - and rockstar was not on it!

So here's my request to add it to 99 bottles of beer!

**Comment by dylanbeattie** [comment]
According to https://www.99-bottles-of-beer.net/submitnewlanguage.html, there are currently 3,442 languages in their queue awaiting approval.

![image](https://github.com/RockstarLang/rockstar/assets/106178/de377007-6075-4ceb-a51f-bd79782d3c90)

So... if anybody wants to add Rockstar to the queue, go ahead, but for all we know it's already in there...
