### ISSUE TITLE
Lock-free Zygohistomorphic Prepropomorphisms for 99-Bottles-Of-Beer-On-The-Wall™ solutions

### ISSUE THREAD

**Issue by Iquerno** [RockstarLang/rockstar#322]
Issue: There is no Built-in™ 99-Bottles-Of-Beer-On-The-Wall™-ready solution for semi-mutual recursion of song lyrics

**Comment by HackerDaGreat57** [comment]
What

**Comment by dylanbeattie** [comment]
Lock-free zygohistomorphic prepropomorphisms sounds like a terrible idea... anybody could just pick them up and walk off with them. We'll keep them locked if it's all the same to you.
