### ISSUE TITLE
String modulus should be like string.strip()

### ISSUE THREAD

**Issue by stevebrown2600** [RockstarLang/rockstar#339]
"abcabcd" % "ab" = "ccd"

**Comment by caseyc37** [comment]
"babab" % "bab" = ???

"ba" or "ab"?

**Comment by stevebrown2600** [comment]
I guess whatever the norm is for string strip functions in other languages? I'd assume you go left to right, so "ab", but I don't think it's ever come up for me.

**Comment by dylanbeattie** [comment]
Rockstar doesn't have a modulus operator %, so while overloading it to work on strings is a nice idea, that would mean adding it first, and if we did that it would spoil the fun of having to write your own modulus function in order to do FizzBuzz.
