### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by moreheadm** [RockstarLang/rockstar#34]
Are language elements is rockstar case sensitive. Some of the example suggest that keywords are case insensitive. Are proper nouns case insensitive except for there first letter? This should probably be clarified in the README.

**Comment by ep12** [comment]
I'd suggest that they are case insensitive somewhere in a line but must start with a capital letter if they are the first word of a line

**Comment by young-steveo** [comment]
@cwfitzgerald My issue is with the spec saying: "Proper variable names can contain spaces as long as each space is followed by an uppercase letter."  I think this should be true for defining variables, assigning them, and referencing them.

Also this makes referencing `Billie Jean` in my parser easier since I also don't have to look for `billie Jean`, `billie jean`, or `Billie jean`.

**Comment by cwfitzgerald** [comment]
@young-steveo Wait, what is the problem then, that is true for all of those cases.

**Comment by young-steveo** [comment]
The problem is that the spec's "examples" currently reference `My world` and `my world` as if they are the same, while the spec text says that the variable identifier should be `My World`.

**Comment by yanorestes** [comment]
You're mixing common variables with proper variables. Proper variables always need proper casing (Billie Jean must always be Billie Jean, not Billie jean). `My world`, however, should always be treated as `my world`. It is not case insensitive (it can't be `My World`), but the `M` must be capitalized if it's on the beginning of a line.

**Comment by young-steveo** [comment]
Hmm... I guess I missed the part of the spec that specifies the first word of every line being capitalized (or maybe this is just imploed in the examples?)

**Comment by yanorestes** [comment]
Oh, it's just implied in the examples, but I don't think it's obligatory. Anyway, it doesn't matter, the fact is proper variables always have to follow-up proper capitalization (Bob Dylan) and common variables may start with a capitalized letter if it's on the beggining of a line (in this case, it should be interpreted as all lowercase)
