### ISSUE TITLE
Block syntax proposal

### ISSUE THREAD

**Issue by wolfgang42** [RockstarLang/rockstar#35]
Currently, Rockstar implements blocks as starting with `If`, `While`, `Until`, or `... taking` and ending with a blank line. This requires multiple blank lines to end multiple blocks, and results in awkward-looking runs of whitespace.

Here's my 2¢ suggestion about how this could work instead:

* For flow control statements (`If`, `While`, `Until`):
    * by default, flow control operations only work on the following statement.
    * To start a block, end the line with `then`, `let's`, `i'll`, `do`
    * To end a block: `take it to the top`, `end if/while/until` (additional keyword suggestions appreciated)
        * If an outer block is ended, the inner block will also end (so `take it to the top` ends an `If` inside a `While`)
        * End of file ends all blocks
* For functions:
    * Functions always start a block
    * If there is no inner block, `Give back` ends the function. (Additional `Give back` statements may be used in inner functions, but a function must always end with a return value.)

Minimalist Rockstar example, full syntax:
```
Modulus takes Number and Divisor
    While Number is as high as Divisor
        Put Number minus Divisor into Number
    Give back Number

Limit is 100
Counter is 0
Fizz is 3
Buzz is 5
Until Counter is Limit do
    Build Counter up
    If Modulus taking Counter, Fizz is 0 and Modulus taking Counter, Buzz is 0 do
        Say "FizzBuzz!"
        Continue
    End if
    If Modulus taking Counter and Fizz is 0 do
        Say "Fizz!"
        Continue
    End if
    If Modulus taking Counter and Buzz is 0 do
        Say "Buzz!"
        Continue
    End if
    Say Counter
End
```

Minimalist Rockstar example, leaving out unnecessary end statements:
```
Modulus takes Number and Divisor
    While Number is as high as Divisor
        Put Number minus Divisor into Number
    Give back Number

Limit is 100
Counter is 0
Fizz is 3
Buzz is 5
Until Counter is Limit do
    Build Counter up
    If Modulus taking Counter, Fizz is 0 and Modulus taking Counter, Buzz is 0 do
        Say "FizzBuzz!"
        Continue
    If Modulus taking Counter and Fizz is 0 do
        Say "Fizz!"
        Continue
    If Modulus taking Counter and Buzz is 0 do
        Say "Buzz!"
        Continue
    Say Counter
```

Ideomatic Rockstar example:
```
Midnight takes your heart and your soul
While your heart is as high as your soul
Put your heart without your soul into your heart
Give back your heart

Desire is a lovestruck ladykiller
My world is nothing 
Fire is ice
Hate is water
Until my world is Desire I'll
Build my world up
If Midnight taking my world, Fire is nothing and Midnight taking my world, Hate is nothing let's
Shout "FizzBuzz!"
Take it to the top
If Midnight taking my world, Fire is nothing let's
Shout "Fizz!"
Take it to the top
If Midnight taking my world, Hate is nothing let's
Say "Buzz!"
Take it to the top
Whisper my world
```

Related: #4, #11, #29.

**Comment by dylanbeattie** [comment]
Rockstar 2.0 will introduce a new block syntax - the runs of whitespace have always been a bit of a headache.
