### ISSUE TITLE
Parser interprets "my world", "her world", "your world" as command-line args (should ONLY be "the world")

### ISSUE THREAD

**Issue by caseyc37** [RockstarLang/rockstar#351]
I believe I have found a parser bug.

The array "my world" in the code below does not behave as expected - it does not gather all the inputs - unless the line "Let my words be my world at my beginning" (at the end) is deleted.

```
My beginning is so long ago, completely lost to time
Let my beginning be without my beginning

Rock my world
Listen to my words
While my words aren't silence
  Whisper my world
  Shatter my words
  Rock my words into my world
  Listen to my words

Whisper my world
Let my words be my world at my beginning
Whisper my world
```

**Comment by dylanbeattie** [comment]
Yep - confirmed; the parser should only pick up `the world` and `the outside` as aliases for the command-line `arguments` array, but there's a bug in the grammar definition that means it's picking up `my world`, `your world`, `her world`, etc, etc.

Fix incomingl;

**Comment by dylanbeattie** [comment]
Fixed in https://github.com/RockstarLang/rockstar/releases/tag/v2.0.2
