### ISSUE TITLE
Errors don't propogate correctly in firefox

### ISSUE THREAD

**Issue by mikachelya** [RockstarLang/rockstar#352]
Invalid syntax does not produce an error on firefox, instead the Rock icon spins forever.
Adding a screenshot of the issue, and the console output.

From Dylan: " looks like Firefox's WASM implementation doesn't support exception handling via the .NET /JS interop that the Rockstar engine uses.
I'll need to wrap that up in some try/catch handling so that if the parser encounters an error it doesn't throw an exception up the stack, it'll wrap it in something friendly and pass that back instead."

![Screenshot 2024-12-07 225444](https://github.com/user-attachments/assets/1bedac68-34c3-4a58-aa84-de5e0004532c)
[console-export-2024-12-7_22-56-43.txt](https://github.com/user-attachments/files/18050001/console-export-2024-12-7_22-56-43.txt)

**Comment by mikachelya** [comment]
seems to be at least somewhat resolved now

**Comment by dylanbeattie** [comment]
Upgrading the build pipeline from .NET 8 to .NET 9 appears to have corrected this, so let's assume it was some sort of incompatibility between .NET 8's WASM compiler and Firefox's WASM engine. :)
