### ISSUE TITLE
Documentation of hash elements is the wrong way around

### ISSUE THREAD

**Issue by duckyluuk** [RockstarLang/rockstar#354]
The documentation states:

```
To loop over the hash elements of an array, use for <key> of <array> - this will call the loop once for each element in the hash, setting key to the key of that element. If you need the element values as well, use for <key> and <value> of <array>:
```

However, the following code:
```
rock array

array at "x" = 1
array at "y" = 2

for key of array
 say key
 ```
 
 gives 
 ```
 1
 2
 ```
 
 And the following code
 ```
 rock array

array at "x" = 1
array at "y" = 2

for key and value of array
 say key + " " + value
 ```
 
 gives
 ``` 
 1 x
 2 y
 ```
 
 so the documentation should say
 ```
(...) for <value> of <array> (...) for <value> and <key> of <array>:
 ```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Fixed the documentation to correctly describe the behavior of for...of loop with arrays in Rockstar. Changed the order of <value> and <key> in the explanation to match the actual behavior.

You can review changes in this commit: https://github.com/mnmnk43434/RockstarLang-rockstar-354/commit/53de54538780c1a41edceffe9dfd31422cc2611d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by dylanbeattie** [comment]
Fixed in https://github.com/RockstarLang/rockstar/commit/4dce2820cc748b52b3edbc6792f4daaf4fec39de
