### ISSUE TITLE
Possible sticker design

### ISSUE THREAD

**Issue by ThomasMPorter** [RockstarLang/rockstar#36]
This project is awesome, felt inspired:

<img width="811" alt="196cd5bc-b475-44ee-8bc1-d937d1bbadfe" src="https://user-images.githubusercontent.com/26288003/43051643-b21ddf02-8dd1-11e8-90b5-cd8c30980a5a.png">

**Comment by N-Masi** [comment]
Looks great!

I'm not a digital artist so I made a crappy drawing but I wonder what a logo like [this](http://imgur.com/W9zhaJ3) would look like if rendered professionally.

**Comment by sammax** [comment]
Awesome!
Can we get a version with "developer" instead of "programmer" too? :)

**Comment by ThomasMPorter** [comment]
Here you go!

<img width="980" alt="5ef8b67e-da9f-4fd7-83fe-71ef3c56ad29" src="https://user-images.githubusercontent.com/26288003/43110621-de7bab08-8ea1-11e8-98c1-d3534f75baa6.png">

**Comment by ThomasMPorter** [comment]
Also took a quick stab at N-Mass’s concept 
<img width="753" alt="fffc12c2-b972-4cf3-9741-fe64099354fc" src="https://user-images.githubusercontent.com/26288003/43111177-c06cab78-8ea4-11e8-8b72-b8a14b0fd3d9.png">

**Comment by N-Masi** [comment]
Wow looks awesome!

**Comment by Xesenix** [comment]
![rockstar_developer](https://user-images.githubusercontent.com/2124257/43169070-cfed3486-8f9f-11e8-8d5f-df18019660e7.png)
Some fast concept

**Comment by Xesenix** [comment]
I think I have an even better idea will add it later after I get back from work.

**Comment by Xesenix** [comment]
![rockstardeveloper3](https://user-images.githubusercontent.com/2124257/43222012-02ac7292-904f-11e8-84ad-2df82e68b853.png)

**Comment by peterbrinck** [comment]
If it's going to be a sticker, I like the first one you did, @Xesenix 
It's more clean and sticker-ish, and is way easier to produce

**Comment by Xesenix** [comment]
@peterbrinck if you meant wider aspect ratio you always can do something like this :)
![rockstardeveloper4](https://user-images.githubusercontent.com/2124257/43277624-dc7dbe04-9108-11e8-9254-3d5cd347035f.png)
also, this vector graphic so can be scaled twisted bent etc. and if needed it can be provided as svg with some modifiable text or if you want to go crazy animation ]:->

hmm also I see there kind of logo with that R and star behind

**Comment by PaperFixie** [comment]
This is really slapdash, but I found an open font and gave it a try with a concept that I liked combining the symbols associated with representing code `</>` and the emoticon` \m/`:

<img width="715" alt="rockstar-logo" src="https://user-images.githubusercontent.com/18726093/44179475-f1b7b380-a0ab-11e8-8467-1f25e2362150.png">
