### ISSUE TITLE
Arrays are always falsy

### ISSUE THREAD

**Issue by duckyluuk** [RockstarLang/rockstar#362]
Filled arrays are incorrectly evaluated as falsy:

```
rock arr 1, 2, 3
say arr   ( [ 1, 2, 3 ] )
if arr
say "yes"   (expected to run)
```

This was originally resolved in https://github.com/RockstarLang/rockstar2/issues/5 but seems to have made a return.

**Comment by dylanbeattie** [comment]
Looks like the original fix got lost somewhere along the way. D'oh. Fixed now.
