### ISSUE TITLE
Switching themes on the documentation pages resets to operating system preferences per navigation step or page refresh

### ISSUE THREAD

**Issue by Yewzir** [RockstarLang/rockstar#365]
Greetings @dylanbeattie

Currently, switching from dark to light themes, and vice versa, is a setting that doesn't get remembered. Refreshing the page or navigating to another topic instantly resets the display theme to the operating system preferences.

Kind regards
@Yewzir

**Comment by dylanbeattie** [comment]
Yeah, there's a theme switcher thing built into Just The Docs (the Jekyll theme I used) which doesn't really work... and persisting it between page loads using browser localStorage just makes everything flash horribly when it loads, so I've taken the switcher off.

Dark mode all the way. At least until the JTD thing is fixed.

**Comment by Yewzir** [comment]
> Yeah, there's a theme switcher thing built into Just The Docs (the Jekyll theme I used) which doesn't really work... and persisting it between page loads using browser localStorage just makes everything flash horribly when it loads, so I've taken the switcher off.
> 
> Dark mode all the way. At least until the JTD thing is fixed.

It doesn't really matter anymore now, at least for me. Prior to the interpreter toggles, the light theme made it slightly more comforting to deal with it. Dark mode all the way, absolutely. 😄
