### ISSUE TITLE
Tommy and Gina reserved keywords

### ISSUE THREAD

**Issue by amihaiemil** [RockstarLang/rockstar#41]
I think we should make ``tommy`` and ``gina`` reserved keywords, in the spirit of Bon Jovi fans. 

``tommy`` could denote a class, while ``gina`` could denote an interface.

**Comment by donaldng** [comment]
I second that.

**Comment by dylanbeattie** [comment]
1) we don't have classes (yet)
2) we don't have interfaces (yet)
3) I'm not reserving Tommy for anything that won't make `Tommy used to work on the docks` syntactically valid.

:)

**Comment by amihaiemil** [comment]
@dylanbeattie Well, 

``tommy Used to work on the docks`` could denote the class ``Used to work on the docks``. Maybe without spaces: ``UsedToWorkOnTheDocks``, which better than some of the classes you find in the Java World, anyway :))

**Comment by sorahn** [comment]
maybe that line could be used to extend the `the docks` class.  so then `used to work on` becomes `extends`

**Comment by amihaiemil** [comment]
@sorahn that's actually a pretty good idea! :))
