### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by fvdveen** [RockstarLang/rockstar#56]
For Rockstar to become a semi-usable language there have to be imports, I would suggest using the `taking X from Y in Z` for import syntax, where `X` is a list of symbols to import separated by the `and` keyword, or 'X' and `from` are omitted and the symbols can be accessed via their file name and `Y` and `Z` are a relative path or an absolute path based on some pre-defined variable. We could then use them in multiple ways:
* `taking modulus and fiboacci from math in utils` and then `modulus` and `fibonacci` can be used as normal functions
* `taking math in utils` with this `modulus from math` and `fibonacci from math` can be used as functions.

**Comment by fvdveen** [comment]
BTW love the idea, keep up the good work.

**Comment by wolfgang42** [comment]
For syntax, what about something like "To the tune of"?

**Comment by fvdveen** [comment]
That could work, but could you give a complete example of an import statement and how the symbols would be used?

**Comment by tkdberger** [comment]
* `To the tune of <module>`: similar to Python's `import <module>`
* `To the tune of <module>'s <item>`: similar to Python's `from <module> import <item>`

So `To the tune of math's modulus` would be similar to `from math import modulus`. Although perhaps `Inspired by` lends a better syntax for more than one import? E.g.
```
Inspired by:
math's modulus
foo's bar
util
    
(blank line ends the "inspirations" block, similar to how other Rockstar blocks end)
```

~~Having imports in a block structure admittedly hardly makes sense, but then again we're building a language around rock'n'roll lyrics to confuse recruiters here.~~

**Comment by ep12** [comment]
Also, I've never seen lyrics of a song that starts with "hey, search for the lyrics of that song because we copied half of it." And it is a bit harder for a parser. Leaving that recursive stuff out is not that bad

**Comment by dkolkena** [comment]
I like the idea of using syntax like "Featuring {util} from {lib}!" or "Give a hand for {lib}!" as if it were a live concert.

**Comment by gunnerwolf** [comment]
@aquacash5 has a good suggestion over in #63 

Using `off {filename} play {thing to import}`
This could be equivalent to python's `from X import Y`, or typescript's `import X from Y`, or node's `require(X).Y`

And in the case where you want to import the whole module, just `play {thing to import}`

I think naming-wise, this should work more like python or typescript than node.
Node allows you to name the imported object whatever you please (`const coolVariable = require('fs')`), while python and typescript require you to use the names given in the module (typescript has optional aliases, don't think we need those)

So for example if your other track (module) defines `My Bleeding Heart`, you could `Off 'My Other Track' play 'My Bleeding Heart'`, and it would import My Bleeding Heart from My Other Track, thus when playing (importing) from another track (module), it's expected that you use the names defined in that other track.

Alternatively, of course, `off` could be replaced with `from`, which might work better.

Not sure if idiomatically this works better than @dkolkena's suggestion though.
