### ISSUE TITLE
RSA

### ISSUE THREAD

**Issue by MsMadGirl** [RockstarLang/rockstar#7]
I'd love to see this developed to the point where a song version of RSA encryption would be feasible.

**Comment by stretchyboy** [comment]
Have you got a link to the algorithm? What is the language missing? I say this as I thought 'There is no random()' but there is enough to build a simple RGN function.

**Comment by marcinruszkiewicz** [comment]
https://gist.github.com/JonCooperWorks/5314103 for example (just the first result I found).

As far as I can tell we're mostly missing string/array operations - how to get each letter of a string, letter to ansi, joining an array to a string.

**Comment by stretchyboy** [comment]
There seem to be 3 or 4 array proposals. Has anyone implemented one yet?
Once we get arrays we might just be able to use the array manipulation
syntax on strings like python and JavaScript do
