### ISSUE TITLE
Rockstar C++ interpreter

### ISSUE THREAD

**Issue by hvonck** [RockstarLang/rockstar#79]
I find the rockstar language quite amazing and decided to try to write my own interpreter in C++. It currently does not implement the entire spec yet. But I'm getting there.

You can find more out about my interpreter here: https://github.com/hvonck/rockstar

**Comment by hvonck** [comment]
The interpreter is now basically complete!
Break and continue still need to be implemented, as do pronouns.
But the FizzBuzz example works :)

You can find more out about my interpreter here: https://github.com/hvonck/rockstar

**Comment by cwfitzgerald** [comment]
You should add it to the README and make a PR!
