### ISSUE TITLE
Wants

### ISSUE THREAD

**Issue by zezic** [RockstarLang/rockstar#8]
I don't know how this can be applied, but please consider adding some syntax construction support that will allow to write next line of code:
```rockstart
Polly wants a cracker
```

**Comment by mflodin** [comment]
It could be interpreted as the old meaning of want - i.e. missing. So it would simply initialize Polly to -17 in this case. Could also make `need(s)` a synonym for `want(s)`.

**Comment by zezic** [comment]
Maybe it also can be used as the form of `assert` statement.

**Comment by alwaysblank** [comment]
I feel like the most natural use would be for some kind of type hinting, i.e.:
```
Searching takes Polly, Polly wants a Cracker
```
...where an exception is thrown if `Searching` is invoked where `Polly`'s type !== `Cracker`

**Comment by young-steveo** [comment]
It looks like Rockstar is leaning toward dynamic weak typing, so my vote is that `wants` becomes either a poetic number negation as @mflodin suggests, or maybe it could be an alias of the function keyword `takes`, i.e.:

```
Polly wants a cracker
```

is equivalent to

```
Polly takes a cracker
```

**Comment by cwfitzgerald** [comment]
I agree with @young-steveo, having it be a an alias for takes makes a lot of sense. Additionally, something you can use `need(s)` for negative literals:

```
Polly needs a cracker
```

**Comment by stretchyboy** [comment]
I think wants as an alias for takes is an excellent idea. Writing something with lots of function calls sounds weird at the moment.
