### ISSUE TITLE
Anybody interested in writing a solid Rockstar Interpreter in the PVM?

### ISSUE THREAD

**Issue by Knorrfrieder** [RockstarLang/rockstar#82]
Such a language like Rockstar is very much what the PVM was made to handle. https://en.wikipedia.org/wiki/Parrot_virtual_machine 
Working grammar parser already included in PVM (https://en.wikipedia.org/wiki/Parser_Grammar_Engine). Only the glory details have to be introduced ;)
Maybe somebody has some time left on the weekend?

**Comment by cwfitzgerald** [comment]
Once my front end is done (very shortly) it will be multi backend, so I can add this to my list of targets.
