### ISSUE TITLE
We need a Hall of Fame

### ISSUE THREAD

**Issue by ioxua** [RockstarLang/rockstar#84]
Or somewhere we can show off our rockstar coding abilities. What do you think?

**Comment by cwfitzgerald** [comment]
I think it would be a good idea to have a single place where we can put a bunch of sample rockstar code... doing actual work :)

**Comment by yanorestes** [comment]
I'm still waiting for a rockstar quine...

**Comment by ioxua-os** [comment]
What do you mean by "quine"? Self replicating programs?

**Comment by cwfitzgerald** [comment]
Quine is a program that prints itself.

**Comment by yanorestes** [comment]
Every good language should have a good working quine!

**Comment by ioxua-os** [comment]
> Quine is a program that prints itself.

Oh thanks! I didn't know that

> Every good language should have a good working quine!

I just tried to write one and realized it needs string interpolation in some form. Is there a way to do this without it or may I open an Issue requesting the functionality?
```
P is "P is %s\nSay P"
Say P
```

**Comment by cwfitzgerald** [comment]
This is one of those issues that is harder to deal with for implementations without full recursive decent parsers which as far as I know right now, none of the them have. Additionally you might find that it is hard to "rockify" this construct due to essentially necessary punctuation.

**Comment by wrenoud** [comment]
Wasn't sure where best to put it... but working on some math functions [Rockstar Math Module](https://gist.github.com/wrenoud/6be6f7509c88a3d8f9867ae782fb768f)

**Comment by kennethgoodman** [comment]
@wrenoud 

I have created something similar with a bunch more functions: https://github.com/kennethgoodman/rockstar_math/blob/master/math.rock

**Comment by gunnerwolf** [comment]
Having an (un)official rockstar website would be great, both to show off what people are doing with the language, and also to direct people to the spec and different implementations.

Maybe somebody should use rockstar-js and make the site in rockstar with node

**Comment by cwfitzgerald** [comment]
The webpiler not has a proper backend (instead of being a static site with some js), so it would be very possible to create a thing where people would be able to upload their rockstar projects to.

That being said, as rockstar can't interact with a database right now...or even have arrays right now, that would be difficult. :)

**Comment by kennethgoodman** [comment]
> or even have arrays right now, 

Don't we have: `Object - a collection of named data properties, as in ECMAScript.`

**Comment by cwfitzgerald** [comment]
We do have objects right now, but the only kind you can make are function objects. There is no way to make, call, or use any other kind.

**Comment by yaobinwen** [comment]
> The webpiler now has a proper backend (instead of being a static site with some js), so it would be very possible to create a thing where people would be able to upload their rockstar projects to.

@cwfitzgerald How about a GitHub organization? I just created one ["We-Rockstar-Developers"](https://github.com/We-Rockstar-Developers) and I'm willing to donate it to this programming language. :-)

Just need a nice icon that rocks...
