### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by crusaderky** [RockstarLang/rockstar#86]
It would be nice to be able to manipulate variables whose number is unknown at the moment of writing the program.

# Basic arrays

## Definition
An array is defined as ``<array> contains|is full of|is made of|is filled with <variables>``
Where ``<array>`` is any valid variable name, and ``<variables>`` is an enumeration of variables and/or literals (but not poetic literals) separated by comma and/or "and". Oxford comma (a, b, and c) is also allowed.
To define an empty array, one should use ``contains null`` or any of its possible aliases, e.g. ``is full of nothing``. Worth nothing that ``x is empty`` does not create an array. I would suggest defining ``emptiness`` as a new alias for ``null``.

## Append, prepend, and remove
``put <variable> to|into [the end of|the top of] <array>`` appends a variable at the end of the array. Note that the syntax is overlapping with plain variable assignment, with the difference that ``<array>`` was previously defined as an array.
``put <variable> to|into the start of|the bottom of <array>`` prepends a variable at the beginning of the array.
``take <variable> out of|away from [the end of|the top of] <array>`` removes the last element from the array and sets the variable with the removed value
``take <variable> out of|away from the start of|the bottom of <array>`` removes the first element from the array and sets the variable with the removed value

## Access by position
``take <variable> out of|away from <array> where <index> is|was|were``
Remove the i-th element of the array and store it into a new variable
``put <variable> out of|away from <array> where <index> is|was|were``
Insert variable before the i-th element of the array, shifting everything right

Read and write into a position without changing the size of the array are superfluous, but happy to hear suggestions.

## Nesting
I'd suggest to dismiss the ability of putting an array inside another array, for the sake of keeping interpreters and transpilers simple.

## Examples
```
Hatred is ice
Lust is fire
My story is Hatred with Lust
A road is journeymaker
My bag is full of Hatred, Lust, and my story
My mouth is filled with nothing
Put Hatred into my mouth
Put my story into the bottom of my bag
Put Hatred into my bag where the road was
Take a gun out of my bag where hatred is
```
transpiles to Python:
```
hatred = 3
lust = 4
story = hatred * lust  # story = 12
road = 2
bag = [hatred, lust, story]  # bag = [3, 4, 12]
mouth = [ ]
mouth.append(hatred)  # mouth = [3]
bag.insert(0, story)  # bag = [12, 3, 4, 12]
bag.insert(road, hatred)  # bag = [12, 3, 3, 4, 12]
gun = bag.pop(hatred)  # bag = [12, 3, 3, 12]; gun = 4
```

**Comment by Mrxx99** [comment]
See #38

**Comment by N-Masi** [comment]
In #38 I defined ways to access and manipulate arrays

**Comment by crusaderky** [comment]
I think neither #38 nor #54 are fit for purpose, as they give no way of defining the array size at runtime or performing indirect access in any way.
For example with them (or with the current Rockstar) it's impossible to write the program "read lines from stdin until you get" stop", then print them out in reverse order ".

Implementation using my suggestion above:

```
My notebook is filled with nothing
Salvation is gone
The words are nothing

While the words ain't  "stop"
Listen to the wind
Put the wind in the notebook
Put the wind in the words
Build Salvation up

Until Salvation is nowhere
Knock Salvation down
Take a prayer out of the notebook where Salvation is
Whisper a prayer

Take a prayer out of the notebook
Whisper a prayer
```

**Comment by erikcorry** [comment]
I like it, but I think the access by position operations should be non-mutating.  This is a much more common operation.

**Comment by erikcorry** [comment]
It seems like a mistake to have the syntax overlap between normal variables and arrays.  Remove this overlap and you can allow nesting without any problems, since the syntax of the operation tells you what type it is expecting to get (and you can throw an exception, sorry,  a tantrum if it doesn't match.

**Comment by Mrxx99** [comment]
In #54 I suggested that arrays behave like lists in e.g. c#. That means it is dynamic and you don't have to define a size before and you can add elements to it later (updated the PR should be more clear now)
Your example should be possible with it too
