### ISSUE TITLE
Say

### ISSUE THREAD

**Issue by ep12** [RockstarLang/rockstar#9]
The documentation is missing the specification that after Say or one of its aliases a literal is also valid. However, it's not clear if poetic numbers are allowed or if the rest of the line is parsed as a string. Requiring quotes at this would be useful for numeric output

**Comment by peteri** [comment]
I have the following idea for say.
Name was Axl Rose
Say "hello " Name 3

would output:
`Hello Axl Rose 3\n`

**Comment by dylanbeattie** [comment]
Poetic literals are only allowed during assignment - it's a very simple operation that is unlikely ever to involve side-effects, IO or any sort of redirection, so I think they're workable here. My hunch is that in any other context you'll rapidly find examples that can't be correctly parsed without some very weird edge cases.

I had the idea that `Say` would actually behave like ToString, with the default behaviour being to write to STDOUT if no output variable is specified, but with the ability write statements like

`Whisper your dreams to the world`

which would take the ToString() representation of whatever's in `your dreams` and put that value into `the world`.
