### ISSUE TITLE
Arithmetic assignments (+=, -=, etc.)

### ISSUE THREAD

**Issue by in2erval** [RockstarLang/rockstar#95]
Does the current specification allow for assignment by arithmetic operations? For example, would:

`Tommy was with a honey from Brooklyn`

be analogous to `Tommy = Tommy + a honey from Brooklyn`?

**Comment by cwfitzgerald** [comment]
No it doesn't, ast from my yet to be released parser

```
00-36 Program
00-36 | Statement List
00-36 | | Set
00-05 | | | Variable: 'Tommy'
10-36 | | | Constant: 41548
```

`Put Tommy with A Honey From Brooklyn into Tommy` is the best I can do:

```
00-47 Program
00-47 | Statement List
00-47 | | Set
42-47 | | | Variable: 'Tommy'
04-36 | | | Addition
04-09 | | | | Variable: 'Tommy'
15-36 | | | | Variable: 'A Honey From Brooklyn'
```

**Comment by in2erval** [comment]
Ah dang, would be nice to see this in the specification. Since

`My world is nothing without your love`

is a valid operation with `My world = 0 - your love` (instead of `My world = 6744`), it'd make sense to allow for the arithmetic keywords to be treated separately as well!

**Comment by dylanbeattie** [comment]
That's a nice idea. We'll play around with it, see what it might break.

**Comment by young-steveo** [comment]
`was with` and `was without` seem pretty idiomatic for `+=` and `-=`

**Comment by cwfitzgerald** [comment]
This seems to conflict with #117 as `with` and `without` are Reserved Words, allowed within Poetic Number Literals.
